The data is currently stored as `.xls` files. In this notebook, we will implement some code to manipulate the data as `pandas.Dataframes` and store as more efficient `.parquet` files on disk.

In [ ]:
#!pip install pyarrow

In [1]:
# import any required libraries here
import pandas as pd # pannel datasets
import pyarrow as pa
import pyarrow.parquet as pq

First, we need to read the `.xls` files into `pandas.Dataframes`. You can use [pandas.read_excel](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html) for this.

In [2]:
# load the building data 
# load the data using pandas
# consider the different number of header rows!
Path = 'C:/Users/Mridul V Koshy/Documents/casestudies/students/raw_data/true/'

#Chemie = pd.read_excel(Path + 'Chemie.xlsx')
#HGII = pd.read_excel(Path + 'HGII.xlsx')
#OH12 = pd.read_excel(Path + 'OH12.xlsx')
#OH14 = pd.read_excel(Path + 'OH14.xlsx')
#Kito = pd.read_excel(Path + 'Kita.xlsx')
Gross = pd.read_excel(Path + 'Gross.xlsx')

Next, we need to implement a function that takes a `pandas.Dataframe` and a path string as an input and writes the data to disk as a `parquet` file. You can use the [PyArrow library](https://arrow.apache.org/docs/python/parquet.html) for this:

In [3]:
def write_as_parquet(df, path):
    # implement this function and add a short doc string describing its use
    name =[x for x in globals() if globals()[x] is df][0]
    table = pa.Table.from_pandas(df)
    pq.write_table(table,path + name + '.parquet')

In [4]:
#write_as_parquet(HGII, Path)
#write_as_parquet(Chemie, Path)
#write_as_parquet(OH12, Path)
#write_as_parquet(OH14, Path)
#write_as_parquet(Kito, Path)
write_as_parquet(Gross, Path)

Now we need the opposite functionality: a function that reads data from a `.parquet` file on disk and returns it as a `pandas.Dataframe`. Implement this function such that it can take a list of names of column to load as an _optional_ parameter.

In [5]:
def load_to_pandas(path, columns):
    # implement this function and add a short doc string describing its use      
    if not columns:
        df = pq.read_pandas(path).to_pandas()
    else:
        df = pq.read_pandas(path, columns=columns).to_pandas()
    return df

In [6]:
columns= []

In [7]:
#columns = ['Date', 'Wärmeenergie Tarif 1']
#HGIIpar = load_to_pandas(Path + 'HGII.parquet', columns)
#Chemiepar = load_to_pandas(Path + 'Chemie.parquet', columns)
#OH12par = load_to_pandas(Path + 'OH12.parquet', columns)
#OH14par = load_to_pandas(Path + 'OH14.parquet', columns)
#Kitapar = load_to_pandas(Path + 'Kito.parquet', columns)
Grosspar = load_to_pandas(Path + 'Gross.parquet', columns)

In [8]:
Grosspar

,Date,Wärmeenergie Tarif 1,Durchfluss,Volumen,Vorlauftemperatur,Rücklauftemperatur,Temperaturdifferenz,Wärmeleistung,Wärmeenergie Tarif 1.1,Durchfluss.1,...,WV- Arbeit tariflos,WV- Arbeit Tarif 1,WV+ Arbeit tariflos,WV+ Arbeit Tarif 1,WV+ Arbeit tariflos.1,WV+ Arbeit Tarif 1.1,WV+ Arbeit tariflos.2,WV+ Arbeit Tarif 1.2,WV- Arbeit tariflos.1,WV- Arbeit Tarif 1.1
0,2021-10-24 08:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1952.4022,1952.4022,67.6970,67.6970,116.1866,116.1866,21.3239,21.3239,2121.747,2121.747
1,2021-10-24 08:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-10-24 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-10-24 09:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-10-24 09:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25696,2022-07-19 01:30:00,4185.0,0.0,649.077,33.1,33.2,-0.1,0.0,4950.0,0.0,...,NaN,NaN,278.2044,278.2044,471.4600,471.4600,553.0929,553.0929,NaN,NaN
25697,2022-07-19 01:45:00,4185.0,0.0,649.077,32.9,33.1,-0.1,0.0,4950.0,0.0,...,NaN,NaN,278.2113,278.2113,471.4730,471.4730,553.1054,553.1054,NaN,NaN
25698,2022-07-19 02:00:00,4185.0,0.0,649.077,33.0,33.1,0.0,0.0,4950.0,0.0,...,NaN,NaN,278.2182,278.2182,471.4792,471.4792,553.1179,553.1179,NaN,NaN
25699,2022-07-19 02:15:00,4185.0,0.0,649.077,32.8,33.1,-0.2,0.0,4950.0,0.0,...,NaN,NaN,278.2251,278.2251,471.4936,471.4936,553.1303,553.1303,NaN,NaN
25700,2022-07-19 02:30:00,4185.0,0.0,649.077,32.7,32.9,-0.1,0.0,4950.0,0.0,...,NaN,NaN,278.2320,278.2320,471.5120,471.5120,553.1428,553.1428,NaN,NaN

Great! We can now store data more efficiently on disk and know how to load it again. Store all the data we have as one `.parquet` file per building.